package ssm.exc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ssm.exc.po.ExamItem;
import ssm.exc.po.ExamItemExample;
import ssm.exc.po.ExamItemWithBLOBs;

public interface ExamItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int countByExample(ExamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int deleteByExample(ExamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int insert(ExamItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int insertSelective(ExamItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    List<ExamItemWithBLOBs> selectByExampleWithBLOBs(ExamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    List<ExamItem> selectByExample(ExamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    ExamItemWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ExamItemWithBLOBs record, @Param("example") ExamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ExamItemWithBLOBs record, @Param("example") ExamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByExample(@Param("record") ExamItem record, @Param("example") ExamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByPrimaryKeySelective(ExamItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ExamItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_item
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByPrimaryKey(ExamItem record);
}