package ssm.exc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ssm.exc.po.Mananger;
import ssm.exc.po.ManangerExample;

public interface ManangerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int countByExample(ManangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int deleteByExample(ManangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int deleteByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int insert(Mananger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int insertSelective(Mananger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    List<Mananger> selectByExample(ManangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    Mananger selectByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") Mananger record, @Param("example") ManangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByExample(@Param("record") Mananger record, @Param("example") ManangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByPrimaryKeySelective(Mananger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mananger
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByPrimaryKey(Mananger record);
}