package ssm.exc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ssm.exc.po.Navigator;
import ssm.exc.po.NavigatorExample;

public interface NavigatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int countByExample(NavigatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int deleteByExample(NavigatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int insert(Navigator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int insertSelective(Navigator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    List<Navigator> selectByExample(NavigatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    Navigator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") Navigator record, @Param("example") NavigatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByExample(@Param("record") Navigator record, @Param("example") NavigatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByPrimaryKeySelective(Navigator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigator
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    int updateByPrimaryKey(Navigator record);
}