package ssm.exc.po;

public class Advice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.itemId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private Integer itemid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.itemId
     *
     * @return the value of advice.itemId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.itemId
     *
     * @param itemid the value for advice.itemId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }
}