package ssm.exc.po;

public class FriendKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.sno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friendSno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String friendsno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.sno
     *
     * @return the value of friend.sno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.sno
     *
     * @param sno the value for friend.sno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friendSno
     *
     * @return the value of friend.friendSno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getFriendsno() {
        return friendsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friendSno
     *
     * @param friendsno the value for friend.friendSno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setFriendsno(String friendsno) {
        this.friendsno = friendsno == null ? null : friendsno.trim();
    }
}