package ssm.exc.po;

import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.ownerId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private Integer ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.picture1
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String picture1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.picture2
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String picture2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.picture3
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String picture3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.picture4
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String picture4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.picture5
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String picture5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.createTime
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.level
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.typeId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.available
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.oldPrice
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private Float oldprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.ownerId
     *
     * @return the value of item.ownerId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.ownerId
     *
     * @param ownerid the value for item.ownerId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.picture1
     *
     * @return the value of item.picture1
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getPicture1() {
        return picture1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.picture1
     *
     * @param picture1 the value for item.picture1
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setPicture1(String picture1) {
        this.picture1 = picture1 == null ? null : picture1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.picture2
     *
     * @return the value of item.picture2
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getPicture2() {
        return picture2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.picture2
     *
     * @param picture2 the value for item.picture2
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setPicture2(String picture2) {
        this.picture2 = picture2 == null ? null : picture2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.picture3
     *
     * @return the value of item.picture3
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getPicture3() {
        return picture3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.picture3
     *
     * @param picture3 the value for item.picture3
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setPicture3(String picture3) {
        this.picture3 = picture3 == null ? null : picture3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.picture4
     *
     * @return the value of item.picture4
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getPicture4() {
        return picture4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.picture4
     *
     * @param picture4 the value for item.picture4
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setPicture4(String picture4) {
        this.picture4 = picture4 == null ? null : picture4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.picture5
     *
     * @return the value of item.picture5
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getPicture5() {
        return picture5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.picture5
     *
     * @param picture5 the value for item.picture5
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setPicture5(String picture5) {
        this.picture5 = picture5 == null ? null : picture5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.createTime
     *
     * @return the value of item.createTime
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.createTime
     *
     * @param createtime the value for item.createTime
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.level
     *
     * @return the value of item.level
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.level
     *
     * @param level the value for item.level
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.typeId
     *
     * @return the value of item.typeId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.typeId
     *
     * @param typeid the value for item.typeId
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.available
     *
     * @return the value of item.available
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.available
     *
     * @param available the value for item.available
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.oldPrice
     *
     * @return the value of item.oldPrice
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public Float getOldprice() {
        return oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.oldPrice
     *
     * @param oldprice the value for item.oldPrice
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setOldprice(Float oldprice) {
        this.oldprice = oldprice;
    }
}