package ssm.exc.po;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.picture
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.campus
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String campus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dormitory
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String dormitory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phoneNum
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weChat
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    private String wechat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sno
     *
     * @return the value of user.sno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sno
     *
     * @param sno the value for user.sno
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.picture
     *
     * @return the value of user.picture
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.picture
     *
     * @param picture the value for user.picture
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.campus
     *
     * @return the value of user.campus
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getCampus() {
        return campus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.campus
     *
     * @param campus the value for user.campus
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setCampus(String campus) {
        this.campus = campus == null ? null : campus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dormitory
     *
     * @return the value of user.dormitory
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getDormitory() {
        return dormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dormitory
     *
     * @param dormitory the value for user.dormitory
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setDormitory(String dormitory) {
        this.dormitory = dormitory == null ? null : dormitory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phoneNum
     *
     * @return the value of user.phoneNum
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phoneNum
     *
     * @param phonenum the value for user.phoneNum
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weChat
     *
     * @return the value of user.weChat
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weChat
     *
     * @param wechat the value for user.weChat
     *
     * @mbggenerated Sat May 26 13:49:54 CST 2018
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }
}